
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skilltracker
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  servlet:
    contextPath: /skill-tracker/api/v1/
#springfox:
#  documentation:
#    auto-startup: false